// <auto-generated />
namespace Demo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class fruit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fruit));
        
        string IMigrationMetadata.Id
        {
            get { return "201807251040553_fruit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
